version: "3.9"

services:
  backend:
    build:
      context: ./backend
    container_name: backend-FastApi
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    restart: always

  frontend:
    build:
      context: ./frontend
    container_name: frontend-Vue
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
    restart: always
    command: npm run dev -- --host

  mysql:
    image: mysql:latest
    container_name: TaskTracker-database
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypassword
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
