version: "3.9"

services:
  backend:
    environment:
      - DATABASE_URL=postgresql+asyncpg://myuser:mypassword@postgres:5432/mydatabase
    build:
      context: ./backend
    container_name: backend-FastApi
    ports:
      - "8000:8000"
    volumes:
      - ./backend/app:/app/app
    restart: always
    depends_on:
      - postgres

  frontend:
    build:
      context: ./frontend
    container_name: frontend-Vue
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    command: npm run dev -- --host
    restart: always

  postgres:
    image: postgres:15
    container_name: TaskTracker-database
    restart: always
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  pg_data:
